POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Fernando",
  "email": "fefe@gmail.com",
  "password": "fefe12345678"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "fefe@gmail.com",
  "password": "fefe12345678"
}

###

GET http://localhost:8080/home
Authorization: Bearer SeuToken
