### GET request to example server
GET http://localhost:8080/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInN1YiI6Imp1anVAZ21haWwuY29tIiwiZXhwIjoxNzY5MzA4ODUwLCJpYXQiOjE3NjkyMjI0NTB9.sDatLM2B28WvN3rNdkGVb6NRVX1F1zSvpjkQ1HCDgc4

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Fernando",
  "email": "fefe@gmail.com",
  "password": "fefe12345678"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "fefe@gmail.com",
  "password": "fefe12345678"
}


###
